package com.nsfl.tpetracker.model.pasta

import java.util.*

class CopyPastaRepository {

    private val copyPastaList = arrayListOf(
            "<i>something wrote in italics</i>",
            "\"What the fuck did you just fucking say about me, you little bot? I'll have you know I graduated top of my draft class in the DSFL, and I've been involved in numerous secret games on Ti-Juana, and I have over 300 confirmed rushing TDs. I am trained in gorilla football and I'm the top rushing QB in the entire league. You are nothing to me but just another O-lineman. I will rush the fuck past you with handedness the likes of which has never been seen before in this game, mark my fucking words. You think you can get away with saying that shit to me over the Discord? Think again, fucker. As we speak I am contacting my secret network of Ryan Leaf Sr. and your LR is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your playoff hopes. You're fucking inactive, kid. I can be anywhere, anytime, and I can score on you in over eighty-seven yards, and that's just with my bare handedness. Not only am I extensively trained in offense, but I have access to the entire playbook of the Baltimore Hawks and I will use it to its full extent to wipe your miserable little team off the face of the boxscore, you little shit. If only you could have know what unholy retribution your little \"clever\" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the TPE, you goddamn idiot. I will shit points all over you and you will drown in it. You're fucking dead, multi.\"",
            "I love seeing people shit on Ryan Leaf Jr and the Coyotes organization. They have literally no idea what they're talking about, because all they think they know is what they see in the media. First, it was Ryan Leaf Jr's fault, because he was creating discord drama. Then, it was Ryan Leaf Jr, he couldn't control his handedness. Now, it is Ryan's fault, because he's their QB, so he shouldn't talk about his 87-yard touchdown run? And, oh by the way, HE PUT TPE INTO HIS ARM. Like seriously, get a life. I've been a Ryan Leaf Jr fan since I was 5 or 6 years old. Maybe you should check your facts before you talk shit. I'm probably blocking whoever was talking shit, because it's just disrespectful and pointless.",
            "I'm some what of a running ba... Quarterba.... Defensive tackle myself.",
            "I saw Ryan Leaf Jr. at a grocery store in Kansas City yesterday. I told him how cool it was to meet him in person, but I didn't want to be a douche and bother him and ask him for photos or anything.<br><br>He said, \"Oh, like you're doing now?\"<br><br>I was taken aback, and all I could say was \"Huh?\" but he kept cutting me off and going \"huh? huh? huh?\" and closing his hand shut in front of my face. I walked away and continued with my shopping, and I heard him chuckle as I walked off. When I came to pay for my stuff up front I saw him trying to walk out the doors with like fifteen Milky Ways in his hands without paying.<br><br>The girl at the counter was very nice about it and professional, and was like \"Sir, you need to pay for those first.\" At first he kept pretending to be tired and not hear her, but eventually turned back around and brought them to the counter.<br><br>When she took one of the bars and started scanning it multiple times, he stopped her and told her to scan them each individually \"to prevent any electrical infetterence,\" and then turned around and winked at me. I don't even think that's a word. After she scanned each bar and put them in a bag and started to say the price, he kept interrupting her by yawning really loudly.",
            "I think its hilarious u kids talking shit about ryan leaf jr. U wouldn't say this shit to him in Norfolk, hes jacked, not only that but he wears the freshest clothes, eats at the chillest restaurants, and hangs with the hottest dudes. Yall are pathetic lol.",
            "Sources: Leaf beside himself. Driving around downtown KANSAS CITY begging (thru texts) Jenkins' family 4 address to Rose's home",
            "Did you ever hear the tragedy of Ryan Leaf Jr. \"the Wise\"?<br>I thought not. It's not a story the Seawolves would tell you. It's a KC legend.<br>Ryan Leaf Jr. was a QB of the Coyotes, so powerful and so wise he could use the Force to influence the midichlorians to create 87 yard rushing touchdowns... He had such a knowledge of the dark side that he could even keep the teams he cared about from losing.<br>The dark side of the Force is a pathway to many abilities some consider to be unnatural.<br>He became so powerful... the only thing he was afraid of was losing his power, which eventually, of course, he did. Unfortunately, he taught Rose Jenkins everything he knew, then she killed him in his sleep. It's ironic - he could save others from defeat, but not himself.",
            "\"Ryan Leaf Jr on who's faster: him or KC's Rose Jenkins. 'I don't compare myself with anybody,' Then he rolled up his sleeve and showed a tattoo of an 87 yard rushing touchdown in the Prospect Bowl. 'I'll let you interpret that however you want,' Leaf Jr said.\"",
            "KCC after their first win: Terry Taffy yelled out, \"There you go! There you go.\" Quarterback Rose Jenkins gave a look of pleasant surprise. Ryan Leaf Jr yelled out, \"We got a f***ing squad now.\" And before Leaf Jr hit the locker room door, former NSFL great Marquise Brown hugged him and said, \"Y'all look so different.",
            "My girlfriend and I broke up because of Ryan Leaf Jr.'s 87-yard TD.<br><br>We got in a huge fight over it because I was saying how it was good that Leaf was bringing new talent to the NSFL. The fight eventually spilled into other topics and it got really heated. In the heat of the moment I called her a \"TPE banker\", and it was a wrap.<br><br>We dated for two years and were thinking about moving in together. At the time I thought she was the love of my life. And it ended over Ryan Leaf Jr.<br><br>And since all of my friends were also her friends, and she was closer friends with them than I was, they took her side. So I lost all my friends too.<br><br>My best friend called me a few hours after the argument and said he didn't want to hang out with me anymore because it would cause drama.<br><br>The only people I've talked to in like a week are my parents.<br>ok im done",
            "WOW kid you just got r/WOOOOOOSHED!!!! \uD83D\uDE02\uD83D\uDE02\uD83D\uDC40<br><br>\"Woooooshed\" means you didn't get the bread, as in the sound made when the Ryan Leaf Jr \"woooshes\" past you. I bet you're too slow to get it, QUARTERBACK!! \uD83D\uDE24\uD83D\uDE24\uD83D\uDE02<br><br>My 87-yard TD run was so thoughtfully crafted and took me a total of 3 minutes, you SHOULD be clapping. \uD83E\uDD2C What's that? My run is bad? I think that's just because you failed. I outran you, nitwit.\uD83E\uDD2D<br><br>In conclusion, I am posting this to the community known as \"#general\" to claim my internet points in your embarrassment \uD83D\uDE0F. Imbecile. The Germans refer to this action as \"Schadenfreude,\" which means \"harm-joy\" \uD83D\uDE2C\uD83D\uDE32. WOW! \uD83E\uDD2A Another reference I had to explain to you.\uD83E\uDD26\u200D\u2642\uFE0F\u200D\u2642\uFE0F\uD83E\uDD2D I am going to cease this conversation for I do not converse with slow persons.\uD83D\uDE0F\uD83D\uDE02",
            "Handedness: Ryan Leaf Jr.",
            "\"He got me,\" Leaf Jr. said of Jenkins getting the starting role over him. \"That f**king Jenkins boomed me.\" Leaf Jr. added, \"She's so good,\" repeating it four times. He then said he wanted to add Kansas City to the list of teams he relocates this summer.",
            "apology for poor english<br><br>when were you when ryan leaf run 87 yard?<br><br>i was sat in discord eating smegma butter when pdx ping<br><br>'leaf is touchdown'<br><br>'no'",
            "I caught up with leaf last night at a dc bar. He was buff as usual, but he brags about the fumbles he caused and he rants about fake news, and of course the 87 yard td. Oh wait, he boomed me into the Potomac.",
            "<i>ALRIGHTY</i>",
            "The simple and short answer is because I'm a fifteen year old QB/RB/DT who's too popular in his city. I've put myself up on a pedestal due to my popularity in <s>Kansas City</s>Norfolk and so I carry it wherever I go. I'm the guy who I told myself I would never be and I hate it, so I'm trying to change it. I admit my wrongs, I attempt to correct my mistakes, and I'm listening to opinions while keeping myself open to critics. Honestly, the egotistical part just comes from, well, my inflated ego due to having 87 yard TDs, and being at the top in <s>Kansas City</s>Norfolk. Twitch creates a platform of instant gratification for me, and so it's hyper ego inflation at it's finest.",
            "You know what Ryan Leaf Jr, kiss my ass! I'm not normally one to engage with your childish tactics, but I've had more than enough of you. You wanna talk so much shit about me & my teams, brag about all the 87-yard TDs you have, but what have you ever actually done for any of those teams besides ride the coattails of the Rose Jenkins of the world?! You wanna come at me, fine, but you come at my team after I've put in countless hours making this team one that should be feared for seasons to come & that's when I take exception. You are scum & maybe you should take a look in the mirror at your own failed quarterback ventures before you take shots at mine.",
            "I spent my time to get the most money in the league and built my player exactly as instructed by my higher ups and then the \"coach\" turns his back on me. I didn't bust my balls to rack up all these 87 yard TDs just to be embarrassed by my \"coach\". He clearly has no idea what hes doing and without you and Terry Taffy hed be an even bigger joke than he already is. If he wants to publicly apologize to me down the line thats fine but otherwise im not spending a single TPE for this clown.",
            "Leaf too stronk, my player suck, resim !( Every loser ever)<br>You are playing with people who have over 86-yard rushing TD experience. Handle it like a man , understand you suck and improve or fuck off<br>This is litterally the prospect bowl and people whine. People who did nothing in their life and joined as a player and expect something completely done for fun for the first time to work properly<br>You are lucky Oles is so easy going. If I was the admin I would say fuck off and desert the fucking league and let every fucking whiner drown in their own tears<br>",
            "\"Well, the last time Ryan offered me some of his \"secret stuff\" I woke up in an alley behind the statium with no underwear and a tattoo scrawled across my back in a strange language I didn't recognise. All I heard about what happened was from Dorfus. Apparently, Logan caught me dancing inside the statium fountain with no pants on singing \"Singing in the Rain.\" After that, Logan saw me climb over the fence and run off. I wasn't on the news, thank God, but I still have no idea what I did or what this tattoo means to this day. So yeah not really eager to try anymore of Ryan's \"secret stuff\" anytime soon.\"<br>-Apollo Reed Seawolves Teammate",
            "Guys I really wanted to believe that NSFL was not the cesspool of morons all my fellow Leaf fans told me it would be. Unfortunately your sack totals, which I purposely made as easy as humanly possible, tanked harder than a Kardashian marriage. I personally apologise for expecting the bare minimum from you as players. If you look at your stat sheet you will notice that you all have gotten a 50 sack bump as 'extra credit' and no this was not because any of you deserved it but it was infact so I don't get my ass fired when the Commissioner asks me 'hey why the fuck did 50% of your draft class fail an introductory tackling class' to whom I will reply 'hmm I don't know maybe its because these klingons are 18 years old and still giggle every time I say the term 'contact'. I'd like to add that in fact one of you got a 5/100 on this stat sheet for which I salute you. Considering this was 100% bot OLs and the statistical probability of you missing more than 90% WALKING is actually higher than your chances of getting laid, which for this player would be an act of God (please stay out of the gene pool you know who you are). I could have actually taken a shit on the scoreboard, wiped it off on the grass, and I am pretty certain my feces could have picked up more QB pressures than you deliberately tried for. So congratulations, on making me lose faith in the DSFL system, and in humanity.",
            "That's a \"Whoops\" moment",
            "I'm well aware of this.",
            "apology for poor english<br><br>where were you when leaf called up<br><br>I was in igloo drink secret stuff when BigRed ring<br><br>\"leaf is wraith\"<br><br>\"yes\"",
            "I was walking down to the lake<br><br>Where I saw this guy on there<br><br>7 foot tall, full of muscle<br><br>He just smiled and gave me his secret stuff",
            "How do you know a normal drink from Leaf-Cola?<br>It's rather simple, it's the tears of opposing QB's, after Leaf ended their careers.",
            "I almost hit Ryan Leaf Jr. while riding my bike in downtown Yellowknife once. I was turning left off Grand, onto Province, right in front of the Burial Grounds and he had just gotten out of a white SUV, standing in what would be the bike lane. I slammed on my brakes, about to yell \"Hey douche! You don't look for bikes??,\" before realizing it was him. He looked at me with that smile... that fucking Ryan Leaf Jr. smile... and instantly my rage was gone. I don't really get star struck or anything, but it took a second to register that this was Ryan Leaf Jr. and he just stood there, smiling, and so I biked around him, and I was.. happy. It was so weird.",
            "Oh wait. The common theme in this website is...all these 404 errors are the newbies lol. No wonder this website is so laughable.<br><br>Learn the TPE tracker ways boys before it hits you in the face.",
            "There are 3 ways to be declared a bad player:<br>1. Have less TPE than Leaf<br>2. You don't have a corporate sponsor<br>3. You have a bad GM<br><br>That's all.",
            "I'm tired of people hating on Baltimore's players!<br><br>Errol Maddox is LEGENDARY<br><br>Marquees Acho is RELENTLESS<br><br>Walt Green is a BALL HAWK<br><br>Dorfus Jimbo<br><br>Corvo Havran is CLUTCH",
            "\"What the fuck did you just fucking say about me, you little bot? I'll have you know I graduated top of my draft class in the DSFL, and I've been involved in numerous secret games on Myrtle Beach, and I have over 300 confirmed tackles. I am trained in gorilla football and I'm the top tackling LB in the entire league. You are nothing to me but just another O-lineman. I will rush the fuck past you with handedness the likes of which has never been seen before in this game, mark my fucking words. You think you can get away with saying that shit to me over the Discord? Think again, fucker. As we speak I am contacting my secret network of Sisters and your LR is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your playoff hopes. You're fucking inactive, kid. I can be anywhere, anytime, and I can tackle you in over sixty-nine ways, and that's just with my bare handedness. Not only am I extensively trained in defense, but I have access to the entire playbook of the Chicago Butchers and I will use it to its full extent to wipe your miserable little team off the face of the boxscore, you little shit. If only you could have know what unholy retribution your little \" clever \" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the TPE, you goddamn idiot. I will shit points all over you and you will drown in it. You're fucking dead, multi.\"",
            "I have guns big enough to shoot through a brick house and through your fridge and hit you behind it just remember that!"
    )

    private var nextIndex = 0

    fun getNextCopyPasta(): String {
        val pasta = copyPastaList[nextIndex]
        nextIndex++
        nextIndex %= copyPastaList.size
        return pasta
    }

    private val random = Random()

    fun getRandomCopyPasta() = copyPastaList[random.nextInt(copyPastaList.size)]
}