package com.nsfl.tpetracker.model.pasta

import java.util.*

class CopyPastaRepository {

    private val copyPastaList = arrayListOf(
            "<i>something wrote in italics</i>",
            "\"What the fuck did you just fucking say about me, you little bot? I'll have you know I graduated top of my draft class in the DSFL, and I've been involved in numerous secret games on Ti-Juana, and I have over 300 confirmed rushing TDs. I am trained in gorilla football and I'm the top rushing QB in the entire league. You are nothing to me but just another O-lineman. I will rush the fuck past you with handedness the likes of which has never been seen before in this game, mark my fucking words. You think you can get away with saying that shit to me over the Discord? Think again, fucker. As we speak I am contacting my secret network of Ryan Leaf Sr. and your LR is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your playoff hopes. You're fucking inactive, kid. I can be anywhere, anytime, and I can score on you in over eighty-seven yards, and that's just with my bare handedness. Not only am I extensively trained in offense, but I have access to the entire playbook of the Baltimore Hawks and I will use it to its full extent to wipe your miserable little team off the face of the boxscore, you little shit. If only you could have know what unholy retribution your little \"clever\" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the TPE, you goddamn idiot. I will shit points all over you and you will drown in it. You're fucking dead, multi.\"",
            "I love seeing people shit on Ryan Leaf Jr and the Coyotes organization. They have literally no idea what they're talking about, because all they think they know is what they see in the media. First, it was Ryan Leaf Jr's fault, because he was creating discord drama. Then, it was Ryan Leaf Jr, he couldn't control his handedness. Now, it is Ryan's fault, because he's their QB, so he shouldn't talk about his 87-yard touchdown run? And, oh by the way, HE PUT TPE INTO HIS ARM. Like seriously, get a life. I've been a Ryan Leaf Jr fan since I was 5 or 6 years old. Maybe you should check your facts before you talk shit. I'm probably blocking whoever was talking shit, because it's just disrespectful and pointless.",
            "I'm some what of a running ba... Quarterba.... Defensive tackle myself.",
            "I saw Ryan Leaf Jr. at a grocery store in Kansas City yesterday. I told him how cool it was to meet him in person, but I didn't want to be a douche and bother him and ask him for photos or anything.<br><br>He said, \"Oh, like you're doing now?\"<br><br>I was taken aback, and all I could say was \"Huh?\" but he kept cutting me off and going \"huh? huh? huh?\" and closing his hand shut in front of my face. I walked away and continued with my shopping, and I heard him chuckle as I walked off. When I came to pay for my stuff up front I saw him trying to walk out the doors with like fifteen Milky Ways in his hands without paying.<br><br>The girl at the counter was very nice about it and professional, and was like \"Sir, you need to pay for those first.\" At first he kept pretending to be tired and not hear her, but eventually turned back around and brought them to the counter.<br><br>When she took one of the bars and started scanning it multiple times, he stopped her and told her to scan them each individually \"to prevent any electrical infetterence,\" and then turned around and winked at me. I don't even think that's a word. After she scanned each bar and put them in a bag and started to say the price, he kept interrupting her by yawning really loudly.",
            "I think its hilarious u kids talking shit about ryan leaf jr. U wouldn't say this shit to him in Norfolk, hes jacked, not only that but he wears the freshest clothes, eats at the chillest restaurants, and hangs with the hottest dudes. Yall are pathetic lol.",
            "Sources: Leaf beside himself. Driving around downtown KANSAS CITY begging (thru texts) Jenkins' family 4 address to Rose's home",
            "Did you ever hear the tragedy of Ryan Leaf Jr. \"the Wise\"?<br>I thought not. It's not a story the Seawolves would tell you. It's a KC legend.<br>Ryan Leaf Jr. was a QB of the Coyotes, so powerful and so wise he could use the Force to influence the midichlorians to create 87 yard rushing touchdowns... He had such a knowledge of the dark side that he could even keep the teams he cared about from losing.<br>The dark side of the Force is a pathway to many abilities some consider to be unnatural.<br>He became so powerful... the only thing he was afraid of was losing his power, which eventually, of course, he did. Unfortunately, he taught Rose Jenkins everything he knew, then she killed him in his sleep. It's ironic - he could save others from defeat, but not himself.",
            "\"Ryan Leaf Jr on who's faster: him or KC's Rose Jenkins. 'I don't compare myself with anybody,' Then he rolled up his sleeve and showed a tattoo of an 87 yard rushing touchdown in the Prospect Bowl. 'I'll let you interpret that however you want,' Leaf Jr said.\"",
            "KCC after their first win: Terry Taffy yelled out, \"There you go! There you go.\" Quarterback Rose Jenkins gave a look of pleasant surprise. Ryan Leaf Jr yelled out, \"We got a f***ing squad now.\" And before Leaf Jr hit the locker room door, former NSFL great Marquise Brown hugged him and said, \"Y'all look so different.",
            "My girlfriend and I broke up because of Ryan Leaf Jr.'s 87-yard TD.<br><br>We got in a huge fight over it because I was saying how it was good that Leaf was bringing new talent to the NSFL. The fight eventually spilled into other topics and it got really heated. In the heat of the moment I called her a \"TPE banker\", and it was a wrap.<br><br>We dated for two years and were thinking about moving in together. At the time I thought she was the love of my life. And it ended over Ryan Leaf Jr.<br><br>And since all of my friends were also her friends, and she was closer friends with them than I was, they took her side. So I lost all my friends too.<br><br>My best friend called me a few hours after the argument and said he didn't want to hang out with me anymore because it would cause drama.<br><br>The only people I've talked to in like a week are my parents.<br>ok im done",
            "WOW kid you just got r/WOOOOOOSHED!!!! \uD83D\uDE02\uD83D\uDE02\uD83D\uDC40<br><br>\"Woooooshed\" means you didn't get the bread, as in the sound made when the Ryan Leaf Jr \"woooshes\" past you. I bet you're too slow to get it, QUARTERBACK!! \uD83D\uDE24\uD83D\uDE24\uD83D\uDE02<br><br>My 87-yard TD run was so thoughtfully crafted and took me a total of 3 minutes, you SHOULD be clapping. \uD83E\uDD2C What's that? My run is bad? I think that's just because you failed. I outran you, nitwit.\uD83E\uDD2D<br><br>In conclusion, I am posting this to the community known as \"#general\" to claim my internet points in your embarrassment \uD83D\uDE0F. Imbecile. The Germans refer to this action as \"Schadenfreude,\" which means \"harm-joy\" \uD83D\uDE2C\uD83D\uDE32. WOW! \uD83E\uDD2A Another reference I had to explain to you.\uD83E\uDD26\u200D\u2642\uFE0F\u200D\u2642\uFE0F\uD83E\uDD2D I am going to cease this conversation for I do not converse with slow persons.\uD83D\uDE0F\uD83D\uDE02",
            "Handedness: Ryan Leaf Jr.",
            "\"He got me,\" Leaf Jr. said of Jenkins getting the starting role over him. \"That f**king Jenkins boomed me.\" Leaf Jr. added, \"She’s so good,\" repeating it four times. He then said he wanted to add Kansas City to the list of teams he relocates this summer.",
            "apology for poor english<br><br>when were you when ryan leaf run 87 yard?<br><br>i was sat in discord eating smegma butter when pdx ping<br><br>'leaf is touchdown'<br><br>'no'",
            "I caught up with leaf last night at a dc bar. He was buff as usual, but he brags about the fumbles he caused and he rants about fake news, and of course the 87 yard td. Oh wait, he boomed me into the Potomac."
    )

    private val random = Random()

    fun getRandomCopyPasta() = copyPastaList[random.nextInt(copyPastaList.size)]
}
